/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ntek_dpinterface_dpjni */

#ifndef _Included_com_ntek_dpinterface_dpjni
#define _Included_com_ntek_dpinterface_dpjni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ntek_dpinterface_dpjni
 * Method:    led1control
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_ntek_dpinterface_dpjni_led1control
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_ntek_dpinterface_dpjni
 * Method:    led2control
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_ntek_dpinterface_dpjni_led2control
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_ntek_dpinterface_dpjni
 * Method:    speakerMode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ntek_dpinterface_dpjni_speakerMode
  (JNIEnv *, jobject);

/*
 * Class:     com_ntek_dpinterface_dpjni
 * Method:    handsetMode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ntek_dpinterface_dpjni_handsetMode
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
